In [36]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define the neural network model
class NewsClassifier(nn.Module):
    def __init__(self):
        super(NewsClassifier, self).__init__()
        self.layer1 = nn.Linear(6, 3)
        self.layer2 = nn.Linear(3, 3)
        self.layer3 = nn.Linear(3, 4)
        self.relu1 = nn.ReLU()
        self.relu2 = nn.ReLU()

    def forward(self, x):
        x = self.relu1(self.layer1(x))
        x = self.relu2(self.layer2(x))
        x = self.layer3(x)
        return x

# Initialize the model, loss function, and optimizer
model = NewsClassifier()
# Set the predefined weights and biases
model.layer1.weight.data = torch.tensor([
    [0.5, 0.2, 0.3, 0.6, 0.1, 0.7],
    [2, -99, -1, 75, 4.5, -0.01],
    [1, 1, 1, 1, 1, 1]
], dtype=torch.float32)
model.layer1.bias.data = torch.tensor([1.4, 1, 1], dtype=torch.float32)

model.layer2.weight.data = torch.tensor([
    [0.15, 0.1, 0.4],
    [6, 9, 1],
    [2, 2.4, 3]
], dtype=torch.float32)
model.layer2.bias.data = torch.tensor([5, 14, 4.5], dtype=torch.float32)

model.layer3.weight.data = torch.tensor([
    [0.15, 0.1, 0.4],
    [6, 3, 7],
    [1.5, 2, 3.5],
    [0.5, 1.5, 3]
], dtype=torch.float32)
model.layer3.bias.data = torch.tensor([5, 14, 4.5, 4.5], dtype=torch.float32)


criterion = nn.CrossEntropyLoss()

# Set up the data
inputs = torch.tensor([
    [5, 10, 4, 9, -100, -20],
    [7, 3, -55, 18, -1, 0.0007],
    [100, 5, -1000, 20, -200, -5],
    [-1, -1, -1, -1, -1, -5],
], dtype=torch.float32)

labels = torch.tensor([0, 1, 2, 3], dtype=torch.long)

# Train the model
epochs = 1

optimizer = optim.SGD(model.parameters(), lr=1)

for epoch in range(epochs):
    # Train the model for one epoch
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    print(f'Epoch: {epoch}, Loss: {loss.item()}')

# Test the model
testing_inputs = torch.tensor([
    [5, 10, 3, 8, -95, -15],
    [-1, 0, -1, -2, -1, -6],
], dtype=torch.float32)
with torch.no_grad():
    test_outputs = model(testing_inputs)
    predictions = torch.argmax(test_outputs, dim=1)
    print(f'Testing1 Prediction: {predictions[0]}')
    print(f'Testing2 Prediction: {predictions[1]}')

Epoch: 0, Loss: 6005.41259765625
Epoch: 1, Loss: 38019.67578125
Epoch: 2, Loss: 6.500613212585449
Epoch: 3, Loss: 5.752279281616211
Epoch: 4, Loss: 5.0067877769470215
Epoch: 5, Loss: 4.268913745880127
Epoch: 6, Loss: 3.5509438514709473
Epoch: 7, Loss: 2.88181734085083
Epoch: 8, Loss: 2.316114902496338
Epoch: 9, Loss: 1.9142875671386719
Epoch: 10, Loss: 1.6806602478027344
Epoch: 11, Loss: 1.5573360919952393
Epoch: 12, Loss: 1.48981773853302
Epoch: 13, Loss: 1.4501152038574219
Epoch: 14, Loss: 1.425678014755249
Epoch: 15, Loss: 1.4103955030441284
Epoch: 16, Loss: 1.4008649587631226
Epoch: 17, Loss: 1.3949912786483765
Epoch: 18, Loss: 1.391424536705017
Epoch: 19, Loss: 1.3892900943756104
Epoch: 20, Loss: 1.3880290985107422
Epoch: 21, Loss: 1.3872921466827393
Epoch: 22, Loss: 1.386865258216858
Epoch: 23, Loss: 1.3866196870803833
Epoch: 24, Loss: 1.386479139328003
Epoch: 25, Loss: 1.3863990306854248
Epoch: 26, Loss: 1.3863537311553955
Epoch: 27, Loss: 1.386327862739563
Epoch: 28, Loss: 1.38

In [33]:
# Get the model training parameters
params = model.parameters()

# Print the parameter names and their shapes
for param in params:
    # print(name)
    print(param)

Parameter containing:
tensor([[ 5.0000e-01,  2.0000e-01,  3.0000e-01,  6.0000e-01,  1.0000e-01,
          7.0000e-01],
        [-4.3834e+02, -1.1540e+02,  4.4674e+03, -8.3375e+00,  9.0291e+02,
          5.1865e+01],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00]], requires_grad=True)
Parameter containing:
tensor([ 1.4000, -9.3750,  1.0000], requires_grad=True)
Parameter containing:
tensor([[ 1.5000e-01, -1.4961e+03,  4.0000e-01],
        [ 6.0000e+00, -3.2484e+02,  1.0000e+00],
        [ 2.0000e+00, -1.1599e+03,  3.0000e+00]], requires_grad=True)
Parameter containing:
tensor([  -32.3263, -2929.8127,  -783.8051], requires_grad=True)
Parameter containing:
tensor([[ 1.6594e+00,  6.7625e+00,  1.7687e+00],
        [-3.0631e+01, -2.9869e+03, -7.9149e+02],
        [ 3.4623e+01,  2.9346e+03,  7.8752e+02],
        [ 2.4981e+00,  5.2150e+01,  1.6099e+01]], requires_grad=True)
Parameter containing:
tensor([7.0000, 7.0000, 7.0000, 7.0000], requires_

In [37]:
model.layer1.weight.data

tensor([[ 5.0000e-01,  2.0000e-01,  3.0000e-01,  6.0000e-01,  1.0000e-01,
          7.0000e-01],
        [-4.3834e+02, -1.1540e+02,  4.4674e+03, -8.3375e+00,  9.0291e+02,
          5.1865e+01],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00]])

In [38]:
# Get the model training parameters
params = model.state_dict()

# Print the parameter names and their shapes
for name, param in params.items():
    print(name)
    print(param)

layer1.weight
tensor([[ 5.0000e-01,  2.0000e-01,  3.0000e-01,  6.0000e-01,  1.0000e-01,
          7.0000e-01],
        [-4.3834e+02, -1.1540e+02,  4.4674e+03, -8.3375e+00,  9.0291e+02,
          5.1865e+01],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00]])
layer1.bias
tensor([ 1.4000, -9.3750,  1.0000])
layer2.weight
tensor([[ 1.5000e-01, -1.4961e+03,  4.0000e-01],
        [ 6.0000e+00, -3.2484e+02,  1.0000e+00],
        [ 2.0000e+00, -1.1599e+03,  3.0000e+00]])
layer2.bias
tensor([  -32.3263, -2929.8127,  -783.8051])
layer3.weight
tensor([[ 1.6594e+00,  6.7625e+00,  1.7687e+00],
        [-3.0631e+01, -2.9869e+03, -7.9149e+02],
        [ 3.4623e+01,  2.9346e+03,  7.8752e+02],
        [ 2.4981e+00,  5.2150e+01,  1.6099e+01]])
layer3.bias
tensor([7.0000, 7.0000, 7.0000, 7.0000])
