In [30]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define the neural network model
class NewsClassifier(nn.Module):
    def __init__(self):
        super(NewsClassifier, self).__init__()
        self.layer1 = nn.Linear(7, 3)
        self.layer2 = nn.Linear(3, 3)
        self.layer3 = nn.Linear(3, 4)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.layer1(x))
        x = self.relu(self.layer2(x))
        x = self.layer3(x)
        return x

# Initialize the model, loss function, and optimizer
model = NewsClassifier()
# Set the predefined weights and biases
model.layer1.weight.data = torch.tensor([
    [0.5, 0.2, 0.3, 0.6, 0.1, 0.7],
    [2, -99, -1, 75, 4.5, -0.01],
    [1, 1, 1, 1, 1, 1]
], dtype=torch.float32)
model.layer1.bias.data = torch.tensor([0.8, 1000, 1], dtype=torch.float32)

model.layer2.weight.data = torch.tensor([
    [0.15, 0.1, 0.4],
    [6, 9, 1],
    [2, 2.4, 3]
], dtype=torch.float32)
model.layer2.bias.data = torch.tensor([5, 14, 4.5], dtype=torch.float32)

model.layer3.weight.data = torch.tensor([
    [0.15, 0.1, 0.4],
    [6, 3, 7],
    [1.5, 2, 3.5],
    [0.5, 1.5, 3]
], dtype=torch.float32)
model.layer3.bias.data = torch.tensor([5, 14, 4.5, 4.5], dtype=torch.float32)


criterion = nn.CrossEntropyLoss()

# Set up the data
inputs = torch.tensor([
    [5, 10, 4, 9, -100, -20],
    [7, 3, -55, 18, -1, 0.0007],
    [100, 5, -1000, 20, -200, -5],
    [-1, -1, -1, -1, -1, -5],
], dtype=torch.float32)

labels = torch.tensor([0, 1, 2, 3], dtype=torch.long)

# Train the model
epochs = 1

for epoch in range(epochs):
    # Train the model for one epoch
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    print(f'Epoch: {epoch}, Loss: {loss.item()}')

    # Update the model parameters manually
    with torch.no_grad():
        for param in model.parameters():
            param -= param.grad

# Test the model
testing_inputs = torch.tensor([
    [5, 10, 3, 8, -95, -15],
    [-1, 0, -1, -2, -1, -6],
], dtype=torch.float32)
with torch.no_grad():
    test_outputs = model(testing_inputs)
    predictions = torch.argmax(test_outputs, dim=1)
    print(f'Testing1 Prediction: {predictions[0]}')
    print(f'Testing2 Prediction: {predictions[1]}')

Epoch: 0, Loss: 18934.294921875
Testing1 Prediction: 2
Testing2 Prediction: 2


In [31]:
# Get the model training parameters
params = model.state_dict()

# Print the parameter names and their shapes
for name, param in params.items():
    print(name)
    print(param)

layer1.weight
tensor([[ 5.0000e-01,  2.0000e-01,  3.0000e-01,  6.0000e-01,  1.0000e-01,
          7.0000e-01],
        [-4.9149e+02, -2.2171e+02,  4.4249e+03, -1.0402e+02,  1.9660e+03,
          2.6449e+02],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00]])
layer1.bias
tensor([8.0000e-01, 9.7899e+02, 1.0000e+00])
layer2.weight
tensor([[ 1.5000e-01, -4.3463e+03,  4.0000e-01],
        [ 6.0000e+00, -1.1241e+03,  1.0000e+00],
        [ 2.0000e+00, -3.4310e+03,  3.0000e+00]])
layer2.bias
tensor([ 1.0375, 12.6500,  0.9750])
layer3.weight
tensor([[ 7.4300e+00,  5.4630e+02,  1.4625e+02],
        [-8.6870e+01, -8.0283e+03, -2.1353e+03],
        [ 6.0376e+01,  5.1919e+03,  1.3877e+03],
        [ 2.7214e+01,  2.2967e+03,  6.1526e+02]])
layer3.bias
tensor([ 5.2500, 13.2500,  4.7500,  4.7500])
